/**
 * Copyright (c) 2024 CEA LIST.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Obeo - initial API and implementation
 */
package pepper.peppermm.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import pepper.peppermm.util.PepperAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers. The adapters generated by this
 * factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}. The adapters
 * also support Eclipse property sheets. Note that most of the adapters are shared among multiple instances. <!--
 * begin-user-doc --> <!-- end-user-doc -->
 *
 * @generated
 */
public class PepperItemProviderAdapterFactory extends PepperAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
    /**
     * This keeps track of the root adapter factory that delegates to this adapter factory. <!-- begin-user-doc --> <!--
     * end-user-doc -->
     *
     * @generated
     */
    protected ComposedAdapterFactory parentAdapterFactory;

    /**
     * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}. <!-- begin-user-doc --> <!--
     * end-user-doc -->
     *
     * @generated
     */
    protected IChangeNotifier changeNotifier = new ChangeNotifier();

    /**
     * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected Collection<Object> supportedTypes = new ArrayList<>();

    /**
     * This constructs an instance. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    public PepperItemProviderAdapterFactory() {
        this.supportedTypes.add(IEditingDomainItemProvider.class);
        this.supportedTypes.add(IStructuredItemContentProvider.class);
        this.supportedTypes.add(ITreeItemContentProvider.class);
        this.supportedTypes.add(IItemLabelProvider.class);
        this.supportedTypes.add(IItemPropertySource.class);
    }

    /**
     * This keeps track of the one adapter used for all {@link pepper.peppermm.Organization} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected OrganizationItemProvider organizationItemProvider;

    /**
     * This creates an adapter for a {@link pepper.peppermm.Organization}. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createOrganizationAdapter() {
        if (this.organizationItemProvider == null) {
            this.organizationItemProvider = new OrganizationItemProvider(this);
        }

        return this.organizationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link pepper.peppermm.ResourceFolder} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected ResourceFolderItemProvider resourceFolderItemProvider;

    /**
     * This creates an adapter for a {@link pepper.peppermm.ResourceFolder}. <!-- begin-user-doc --> <!-- end-user-doc
     * -->
     *
     * @generated
     */
    @Override
    public Adapter createResourceFolderAdapter() {
        if (this.resourceFolderItemProvider == null) {
            this.resourceFolderItemProvider = new ResourceFolderItemProvider(this);
        }

        return this.resourceFolderItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link pepper.peppermm.Team} instances. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    protected TeamItemProvider teamItemProvider;

    /**
     * This creates an adapter for a {@link pepper.peppermm.Team}. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createTeamAdapter() {
        if (this.teamItemProvider == null) {
            this.teamItemProvider = new TeamItemProvider(this);
        }

        return this.teamItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link pepper.peppermm.InternalStakeholder} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected InternalStakeholderItemProvider internalStakeholderItemProvider;

    /**
     * This creates an adapter for a {@link pepper.peppermm.InternalStakeholder}. <!-- begin-user-doc --> <!--
     * end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createInternalStakeholderAdapter() {
        if (this.internalStakeholderItemProvider == null) {
            this.internalStakeholderItemProvider = new InternalStakeholderItemProvider(this);
        }

        return this.internalStakeholderItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link pepper.peppermm.ExternalStakeholder} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected ExternalStakeholderItemProvider externalStakeholderItemProvider;

    /**
     * This creates an adapter for a {@link pepper.peppermm.ExternalStakeholder}. <!-- begin-user-doc --> <!--
     * end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createExternalStakeholderAdapter() {
        if (this.externalStakeholderItemProvider == null) {
            this.externalStakeholderItemProvider = new ExternalStakeholderItemProvider(this);
        }

        return this.externalStakeholderItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link pepper.peppermm.Person} instances. <!-- begin-user-doc
     * --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected PersonItemProvider personItemProvider;

    /**
     * This creates an adapter for a {@link pepper.peppermm.Person}. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createPersonAdapter() {
        if (this.personItemProvider == null) {
            this.personItemProvider = new PersonItemProvider(this);
        }

        return this.personItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link pepper.peppermm.TagFolder} instances. <!-- begin-user-doc
     * --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected TagFolderItemProvider tagFolderItemProvider;

    /**
     * This creates an adapter for a {@link pepper.peppermm.TagFolder}. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createTagFolderAdapter() {
        if (this.tagFolderItemProvider == null) {
            this.tagFolderItemProvider = new TagFolderItemProvider(this);
        }

        return this.tagFolderItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link pepper.peppermm.TaskTag} instances. <!-- begin-user-doc
     * --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected TaskTagItemProvider taskTagItemProvider;

    /**
     * This creates an adapter for a {@link pepper.peppermm.TaskTag}. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createTaskTagAdapter() {
        if (this.taskTagItemProvider == null) {
            this.taskTagItemProvider = new TaskTagItemProvider(this);
        }

        return this.taskTagItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link pepper.peppermm.Task} instances. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    protected TaskItemProvider taskItemProvider;

    /**
     * This creates an adapter for a {@link pepper.peppermm.Task}. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createTaskAdapter() {
        if (this.taskItemProvider == null) {
            this.taskItemProvider = new TaskItemProvider(this);
        }

        return this.taskItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link pepper.peppermm.Objective} instances. <!-- begin-user-doc
     * --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected ObjectiveItemProvider objectiveItemProvider;

    /**
     * This creates an adapter for a {@link pepper.peppermm.Objective}. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createObjectiveAdapter() {
        if (this.objectiveItemProvider == null) {
            this.objectiveItemProvider = new ObjectiveItemProvider(this);
        }

        return this.objectiveItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link pepper.peppermm.KeyResult} instances. <!-- begin-user-doc
     * --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected KeyResultItemProvider keyResultItemProvider;

    /**
     * This creates an adapter for a {@link pepper.peppermm.KeyResult}. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createKeyResultAdapter() {
        if (this.keyResultItemProvider == null) {
            this.keyResultItemProvider = new KeyResultItemProvider(this);
        }

        return this.keyResultItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link pepper.peppermm.Project} instances. <!-- begin-user-doc
     * --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected ProjectItemProvider projectItemProvider;

    /**
     * This creates an adapter for a {@link pepper.peppermm.Project}. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createProjectAdapter() {
        if (this.projectItemProvider == null) {
            this.projectItemProvider = new ProjectItemProvider(this);
        }

        return this.projectItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link pepper.peppermm.Workpackage} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected WorkpackageItemProvider workpackageItemProvider;

    /**
     * This creates an adapter for a {@link pepper.peppermm.Workpackage}. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createWorkpackageAdapter() {
        if (this.workpackageItemProvider == null) {
            this.workpackageItemProvider = new WorkpackageItemProvider(this);
        }

        return this.workpackageItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link pepper.peppermm.WorkpackageArtefact} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected WorkpackageArtefactItemProvider workpackageArtefactItemProvider;

    /**
     * This creates an adapter for a {@link pepper.peppermm.WorkpackageArtefact}. <!-- begin-user-doc --> <!--
     * end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createWorkpackageArtefactAdapter() {
        if (this.workpackageArtefactItemProvider == null) {
            this.workpackageArtefactItemProvider = new WorkpackageArtefactItemProvider(this);
        }

        return this.workpackageArtefactItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link pepper.peppermm.Risk} instances. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    protected RiskItemProvider riskItemProvider;

    /**
     * This creates an adapter for a {@link pepper.peppermm.Risk}. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createRiskAdapter() {
        if (this.riskItemProvider == null) {
            this.riskItemProvider = new RiskItemProvider(this);
        }

        return this.riskItemProvider;
    }

    /**
     * This returns the root adapter factory that contains this factory. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public ComposeableAdapterFactory getRootAdapterFactory() {
        return this.parentAdapterFactory == null ? this : this.parentAdapterFactory.getRootAdapterFactory();
    }

    /**
     * This sets the composed adapter factory that contains this factory. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
        this.parentAdapterFactory = parentAdapterFactory;
    }

    /**
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public boolean isFactoryForType(Object type) {
        return this.supportedTypes.contains(type) || super.isFactoryForType(type);
    }

    /**
     * This implementation substitutes the factory itself as the key for the adapter. <!-- begin-user-doc --> <!--
     * end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter adapt(Notifier notifier, Object type) {
        return super.adapt(notifier, this);
    }

    /**
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Object adapt(Object object, Object type) {
        if (this.isFactoryForType(type)) {
            Object adapter = super.adapt(object, type);
            if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
                return adapter;
            }
        }

        return null;
    }

    /**
     * This adds a listener. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void addListener(INotifyChangedListener notifyChangedListener) {
        this.changeNotifier.addListener(notifyChangedListener);
    }

    /**
     * This removes a listener. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void removeListener(INotifyChangedListener notifyChangedListener) {
        this.changeNotifier.removeListener(notifyChangedListener);
    }

    /**
     * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}. <!-- begin-user-doc --> <!--
     * end-user-doc -->
     *
     * @generated
     */
    @Override
    public void fireNotifyChanged(Notification notification) {
        this.changeNotifier.fireNotifyChanged(notification);

        if (this.parentAdapterFactory != null) {
            this.parentAdapterFactory.fireNotifyChanged(notification);
        }
    }

    /**
     * This disposes all of the item providers created by this factory. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void dispose() {
        if (this.organizationItemProvider != null)
            this.organizationItemProvider.dispose();
        if (this.resourceFolderItemProvider != null)
            this.resourceFolderItemProvider.dispose();
        if (this.teamItemProvider != null)
            this.teamItemProvider.dispose();
        if (this.internalStakeholderItemProvider != null)
            this.internalStakeholderItemProvider.dispose();
        if (this.externalStakeholderItemProvider != null)
            this.externalStakeholderItemProvider.dispose();
        if (this.personItemProvider != null)
            this.personItemProvider.dispose();
        if (this.tagFolderItemProvider != null)
            this.tagFolderItemProvider.dispose();
        if (this.taskTagItemProvider != null)
            this.taskTagItemProvider.dispose();
        if (this.taskItemProvider != null)
            this.taskItemProvider.dispose();
        if (this.objectiveItemProvider != null)
            this.objectiveItemProvider.dispose();
        if (this.keyResultItemProvider != null)
            this.keyResultItemProvider.dispose();
        if (this.projectItemProvider != null)
            this.projectItemProvider.dispose();
        if (this.workpackageItemProvider != null)
            this.workpackageItemProvider.dispose();
        if (this.workpackageArtefactItemProvider != null)
            this.workpackageArtefactItemProvider.dispose();
        if (this.riskItemProvider != null)
            this.riskItemProvider.dispose();
    }

}
