<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="peppermm" nsURI="http://peppermm" nsPrefix="peppermm">
  <eClassifiers xsi:type="ecore:EClass" name="Organization">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedProjects" upperBound="-1"
        eType="#//Project" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedResourceFolders" upperBound="-1"
        eType="#//ResourceFolder" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceFolder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedResources" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subFolders" upperBound="-1"
        eType="#//ResourceFolder" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Team" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Person"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalStakeholder" eSuperTypes="#//Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalStakeholder" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="goals" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="biography" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTask" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="#//Instant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="#//Instant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="progress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="computeStartEndDynamically"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" upperBound="-1" eType="#//TaskTag"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedPersons" upperBound="-1"
        eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedTeams" upperBound="-1"
        eType="#//Team"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subTasks" upperBound="-1"
        eType="#//Task" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TagFolder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTags" upperBound="-1"
        eType="#//TaskTag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subFolders" upperBound="-1"
        eType="#//TagFolder" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskTag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suffix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//AbstractTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Objective" eSuperTypes="#//AbstractTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedKeyResults" upperBound="-1"
        eType="#//KeyResult" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyResult" eSuperTypes="#//AbstractTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedWorkpackages" upperBound="-1"
        eType="#//Workpackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedObjectives" upperBound="-1"
        eType="#//Objective" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTagFolders" upperBound="-1"
        eType="#//TagFolder" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRisks" upperBound="-1"
        eType="#//Risk" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leadingUnit" eType="#//InternalStakeholder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participantUnits" upperBound="-1"
        eType="#//InternalStakeholder"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="plannifiedClientCopilMeetings"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mainProgramBrick" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//ProjectState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clients" upperBound="-1"
        eType="#//ExternalStakeholder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partners" upperBound="-1"
        eType="#//ExternalStakeholder"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTransverse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leader" eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSensitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contractualStartDate" eType="#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contractualEndDate" eType="#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveStartDate" eType="#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveEndDate" eType="#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contractTermExtension"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="globalCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fundingRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="funding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manpower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eOTP" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statisticOrder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="internalNeed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clientNeed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Workpackage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" eType="#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leader" eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" upperBound="-1"
        eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//WorkpackageArtefact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTasks" upperBound="-1"
        eType="#//Task" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedObjectives" upperBound="-1"
        eType="#//Objective" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="progress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Instant" instanceClassName="java.time.Instant"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Date" instanceClassName="java.time.LocalDate"/>
  <eClassifiers xsi:type="ecore:EClass" name="WorkpackageArtefact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nature" eType="#//WorkpackageArtefactNature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="plannedDeadline" eType="#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveDeadLine" eType="#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInvoiceTrigger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invoiceAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsible" eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isObsolete" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WorkpackageArtefactNature">
    <eLiterals name="Delivrable" literal="DELIVRABLE"/>
    <eLiterals name="Decisional" value="1" literal="DECISIONAL"/>
    <eLiterals name="ProjectReview" value="2" literal="PROJECT_REVIEW"/>
    <eLiterals name="Action" value="3" literal="ACTION"/>
    <eLiterals name="Invoicing" value="4" literal="INVOICING"/>
    <eLiterals name="ExpenseStatement" value="5" literal="EXPENSE_STATEMENT"/>
    <eLiterals name="ClientSatisfaction" value="6" literal="CLIENT_SATISFACTION"/>
    <eLiterals name="Other" value="7" literal="OTHER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Risk">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//RiskKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="criticity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsible" eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationDate" eType="#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//RiskState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workpackages" upperBound="-1"
        eType="#//Workpackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RiskKind">
    <eLiterals name="Manpower" literal="MANPOWER"/>
    <eLiterals name="Machine" value="1" literal="MACHINE"/>
    <eLiterals name="Material" value="2" literal="MATERIAL"/>
    <eLiterals name="Measurement" value="3" literal="MEASUREMENT"/>
    <eLiterals name="Method" value="4" literal="METHOD"/>
    <eLiterals name="Mission" value="5" literal="MISSION"/>
    <eLiterals name="Management" value="6" literal="MANAGEMENT"/>
    <eLiterals name="Maintenance" value="7" literal="MAINTENANCE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RiskState">
    <eLiterals name="OnGoing" literal="ON_GOING"/>
    <eLiterals name="UnderInstruction" value="1" literal="UNDER_INSTRUCTION"/>
    <eLiterals name="StopBeforeTerm" value="2" literal="STOP_BEFORE_TERM"/>
    <eLiterals name="Completed" value="3" literal="COMPLETED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProjectState">
    <eLiterals name="OnGoing" literal="ON_GOING"/>
    <eLiterals name="UnderInstruction" value="1" literal="UNDER_INSTRUCTION"/>
    <eLiterals name="StopBeforeTerm" value="2" literal="STOP_BEFORE_TERM"/>
    <eLiterals name="Completed" value="3" literal="COMPLETED"/>
  </eClassifiers>
</ecore:EPackage>
